### ISSUE TITLE
Question: purpose of writing the result to other folder

### ISSUE THREAD

**Issue by atsu85** [MeirionHughes/gulp-aurelia-template-lint#5]
Hi,
I'd like to know if there are currently reasons to use following
`.pipe(gulp.dest('output'))`
as shown in example?

I understand that You (@MeirionHughes) had some initial plans to add some additional information for linter to templates, that should be removed after linter does it's work, but I suspect that with TypeScript You probably don't have such plans any more?

**Comment by MeirionHughes** [comment]
well basically it was to show it could simply be inserted into your existing pipeline; which I would imagine is to copy html from the source folder to the output/dist folder. At present  it should always complete that task regardless of any lint error. 

I don't really want to go the path of adding syntax to templates that then need removing; which is why I have asked for typing to be included in aurelia's "binding" syntax. See: https://github.com/aurelia/templating/issues/399

So to answer your question; there is no reason appart from when you copy html to an output path. If you don't need to do that you don't have to; the out html is unchanged after linting and I will do shrive to ensure that never changes.
